<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class GermanWordsSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();
        
        $words = [
            [
                'kapital' => 'A',
                'german_word' => 'Apfel',
                'word_type' => 'Nomen',
                'artikel' => 'der',
                'meaning' => 'apel',
                'plural_form' => 'die Äpfel',
                'present_form' => null,
                'partizip_2' => null,
                'hilfsverb' => null,
                'case' => null,
                'preposition' => null,
                'is_reflexive' => false,
                'is_separable' => false,
                'is_countable' => true,
                'example' => 'Der Apfel ist rot.',
                'additional_notes' => 'Buah yang umum di Jerman',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kapital' => 'A',
                'german_word' => 'aus|gehen',
                'word_type' => 'Verb',
                'artikel' => null,
                'meaning' => 'pergi keluar',
                'plural_form' => null,
                'present_form' => 'ich gehe aus, du gehst aus, er geht aus',
                'partizip_2' => 'ausgegangen',
                'hilfsverb' => 'sein',
                'case' => null,
                'preposition' => null,
                'is_reflexive' => false,
                'is_separable' => true,
                'is_countable' => false,
                'example' => 'Ich gehe heute Abend aus.',
                'additional_notes' => 'Trennbares Verb',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kapital' => 'B',
                'german_word' => 'Buch',
                'word_type' => 'Nomen',
                'artikel' => 'das',
                'meaning' => 'buku',
                'plural_form' => 'die Bücher',
                'present_form' => null,
                'partizip_2' => null,
                'hilfsverb' => null,
                'case' => null,
                'preposition' => null,
                'is_reflexive' => false,
                'is_separable' => false,
                'is_countable' => true,
                'example' => 'Das Buch ist interessant.',
                'additional_notes' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kapital' => 'E',
                'german_word' => 'erinnern',
                'word_type' => 'Verb',
                'artikel' => null,
                'meaning' => 'mengingat',
                'plural_form' => null,
                'present_form' => 'ich erinnere mich, du erinnerst dich, er erinnert sich',
                'partizip_2' => 'erinnert',
                'hilfsverb' => 'haben',
                'case' => null,
                'preposition' => 'an + Akkusativ',
                'is_reflexive' => true,
                'is_separable' => false,
                'is_countable' => false,
                'example' => 'Ich erinnere mich an meinen ersten Schultag.',
                'additional_notes' => 'Reflexives Verb mit Präposition "an"',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kapital' => 'G',
                'german_word' => 'groß',
                'word_type' => 'Adjektiv',
                'artikel' => null,
                'meaning' => 'besar',
                'plural_form' => null,
                'present_form' => null,
                'partizip_2' => null,
                'hilfsverb' => null,
                'case' => null,
                'preposition' => null,
                'is_reflexive' => false,
                'is_separable' => false,
                'is_countable' => false,
                'example' => 'Das ist ein großes Haus.',
                'additional_notes' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kapital' => 'I',
                'german_word' => 'in',
                'word_type' => 'Präposition',
                'artikel' => null,
                'meaning' => 'di dalam',
                'plural_form' => null,
                'present_form' => null,
                'partizip_2' => null,
                'hilfsverb' => null,
                'case' => 'Akkusativ/Dativ',
                'preposition' => null,
                'is_reflexive' => false,
                'is_separable' => false,
                'is_countable' => false,
                'example' => 'Ich gehe in die Schule. (Akk) / Ich bin in der Schule. (Dat)',
                'additional_notes' => 'Wechselpräposition',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kapital' => 'K',
                'german_word' => 'Katze',
                'word_type' => 'Nomen',
                'artikel' => 'die',
                'meaning' => 'kucing',
                'plural_form' => 'die Katzen',
                'present_form' => null,
                'partizip_2' => null,
                'hilfsverb' => null,
                'case' => null,
                'preposition' => null,
                'is_reflexive' => false,
                'is_separable' => false,
                'is_countable' => true,
                'example' => 'Die Katze schläft.',
                'additional_notes' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kapital' => 'L',
                'german_word' => 'langsam',
                'word_type' => 'Adverb',
                'artikel' => null,
                'meaning' => 'pelan',
                'plural_form' => null,
                'present_form' => null,
                'partizip_2' => null,
                'hilfsverb' => null,
                'case' => null,
                'preposition' => null,
                'is_reflexive' => false,
                'is_separable' => false,
                'is_countable' => false,
                'example' => 'Er fährt langsam.',
                'additional_notes' => 'Bisa juga digunakan sebagai adjektiv',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kapital' => 'M',
                'german_word' => 'mit|bringen',
                'word_type' => 'Verb',
                'artikel' => null,
                'meaning' => 'membawa serta',
                'plural_form' => null,
                'present_form' => 'ich bringe mit, du bringst mit, er bringt mit',
                'partizip_2' => 'mitgebracht',
                'hilfsverb' => 'haben',
                'case' => 'Akkusativ',
                'preposition' => null,
                'is_reflexive' => false,
                'is_separable' => true,
                'is_countable' => false,
                'example' => 'Ich bringe einen Kuchen mit.',
                'additional_notes' => 'Trennbares Verb',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kapital' => 'O',
                'german_word' => 'oder',
                'word_type' => 'Konjunktion',
                'artikel' => null,
                'meaning' => 'atau',
                'plural_form' => null,
                'present_form' => null,
                'partizip_2' => null,
                'hilfsverb' => null,
                'case' => null,
                'preposition' => null,
                'is_reflexive' => false,
                'is_separable' => false,
                'is_countable' => false,
                'example' => 'Möchtest du Tee oder Kaffee?',
                'additional_notes' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kapital' => 'S',
                'german_word' => 'schnell',
                'word_type' => 'Adjektiv',
                'artikel' => null,
                'meaning' => 'cepat',
                'plural_form' => null,
                'present_form' => null,
                'partizip_2' => null,
                'hilfsverb' => null,
                'case' => null,
                'preposition' => null,
                'is_reflexive' => false,
                'is_separable' => false,
                'is_countable' => false,
                'example' => 'Das ist ein schnelles Auto.',
                'additional_notes' => 'Bisa juga digunakan sebagai adverb',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kapital' => 'T',
                'german_word' => 'Tisch',
                'word_type' => 'Nomen',
                'artikel' => 'der',
                'meaning' => 'meja',
                'plural_form' => 'die Tische',
                'present_form' => null,
                'partizip_2' => null,
                'hilfsverb' => null,
                'case' => null,
                'preposition' => null,
                'is_reflexive' => false,
                'is_separable' => false,
                'is_countable' => true,
                'example' => 'Der Tisch ist aus Holz.',
                'additional_notes' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kapital' => 'U',
                'german_word' => 'unter',
                'word_type' => 'Präposition',
                'artikel' => null,
                'meaning' => 'di bawah',
                'plural_form' => null,
                'present_form' => null,
                'partizip_2' => null,
                'hilfsverb' => null,
                'case' => 'Akkusativ/Dativ',
                'preposition' => null,
                'is_reflexive' => false,
                'is_separable' => false,
                'is_countable' => false,
                'example' => 'Die Katze liegt unter dem Tisch. (Dat) / Die Katze läuft unter den Tisch. (Akk)',
                'additional_notes' => 'Wechselpräposition',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kapital' => 'V',
                'german_word' => 'verstehen',
                'word_type' => 'Verb',
                'artikel' => null,
                'meaning' => 'mengerti',
                'plural_form' => null,
                'present_form' => 'ich verstehe, du verstehst, er versteht',
                'partizip_2' => 'verstanden',
                'hilfsverb' => 'haben',
                'case' => 'Akkusativ',
                'preposition' => null,
                'is_reflexive' => false,
                'is_separable' => false,
                'is_countable' => false,
                'example' => 'Ich verstehe die deutsche Sprache.',
                'additional_notes' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kapital' => 'W',
                'german_word' => 'weil',
                'word_type' => 'Konjunktion',
                'artikel' => null,
                'meaning' => 'karena',
                'plural_form' => null,
                'present_form' => null,
                'partizip_2' => null,
                'hilfsverb' => null,
                'case' => null,
                'preposition' => null,
                'is_reflexive' => false,
                'is_separable' => false,
                'is_countable' => false,
                'example' => 'Ich lerne Deutsch, weil ich in Deutschland studieren möchte.',
                'additional_notes' => 'Nebensatzkonjunktion - verba di akhir kalimat',
                'created_at' => $now,
                'updated_at' => $now
            ],
        ];

        DB::table('vocabs')->insert($words);
    }
}